### ISSUE TITLE
Kendo window has no method 'destroy'

### ISSUE THREAD

**Issue by rogerfar** [kendo-labs/angular-kendo#167]
When I implement routing and I have a controller like this:

```
myapp.controller('Ctrl1', ['$scope', '$location'
function ($scope, $location) {
    $scope.loadingWindow = null;

    $scope.openWindow = function () {
        $scope.loadingWindow.center().open();
    };

    $scope.closeWindow = function () {
        $scope.loadingWindow.close();
    };
}]);
```

With this HTML:

```
<div data-kendo-window="loadingWindow"
     data-k-width="600"
     data-k-title="false"
     data-k-animation="false"
     data-k-draggable="false"
     data-k-modal="true"
     data-k-resizable="false"
     data-k-visible="false">
    Loading
</div>
```

When I navigate away from the page with a route change I get the following exception:

```
TypeError: Object submitWindow has no method 'destroy'
    at HTMLDivElement.<anonymous> (http://localhost:57822/Scripts/kendo/2013.3.1119/kendo.web.min.js:11:30854)
    at Function.jQuery.extend.each (http://localhost:57822/Scripts/jquery-2.0.3.js:590:23)
    at jQuery.fn.jQuery.each (http://localhost:57822/Scripts/jquery-2.0.3.js:237:17)
    at Object.ct.destroy (http://localhost:57822/Scripts/kendo/2013.3.1119/kendo.web.min.js:11:30800)
    at l.extend.destroy (http://localhost:57822/Scripts/kendo/2013.3.1119/kendo.web.min.js:31:8127)
    at http://localhost:57822/Scripts/angular-kendo.js:265:22
    at Scope.$broadcast (http://localhost:57822/Scripts/angular.js:12239:28)
    at Scope.$destroy (http://localhost:57822/Scripts/angular.js:11908:14)
    at cleanupLastView (http://localhost:57822/Scripts/angular-route.js:841:26)
    at http://localhost:57822/Scripts/angular-route.js:871:15 
```

**Comment by m-sirajuddin-bm** [comment]
Kendo List box issue.. please help

Uncaught TypeError: Cannot read property 'removeData' of null
    at init.destroy (kendo.all.min.js:26)
    at init.destroy (kendo.all.min.js:37)
    at init._destroySelectable (kendo.all.min.js:53)
    at init.destroy (kendo.all.min.js:53)
    at HTMLSelectElement.<anonymous> (kendo.all.min.js:26)
    at Function.each (common.min.js:1)
    at re.fn.init.each (common.min.js:1)
    at Object.ve.destroy (kendo.all.min.js:26)
    at init.content (kendo.all.min.js:46)
    at init.<anonymous> (kendo.all.min.js:46)
